/* eslint-disable no-unused-vars */
import { useState } from 'react';
import { Activity, ArrowRight, CalendarCheck, ChevronDown, ClipboardList, FileText, HeartPulse, MessageSquare, ShieldCheck, Stethoscope, Video } from 'lucide-react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Button from '../components/Button';
import { getDoctors } from '../services/mockApi';

const services = [
    ['Virtual consultations', 'Meet qualified practitioners through a guided, frontend-only consultation room.', Video, 'blue'],
    ['Doctor scheduling', 'Find a specialist, compare availability, and reserve a consultation in a few steps.', CalendarCheck, 'green'],
    ['Remote monitoring', 'Keep fictional health trends organized between appointments and care check-ins.', Activity, 'violet'],
    ['Digital prescriptions', 'Review structured medication instructions and care plans from your dashboard.', FileText, 'amber'],
    ['Medical records', 'Bring consultations, lab reports, and doctor notes into one searchable view.', ClipboardList, 'blue'],
    ['Live availability', 'See practitioner availability states and choose the right moment to connect.', HeartPulse, 'green'],
    ['Healthcare analytics', 'Give care teams a clear operational view of appointments and service health.', Activity, 'violet'],
    ['Patient support', 'Surface reminders, notifications, and next steps without adding friction.', MessageSquare, 'amber'],
];
const faqs = ['How can I book a doctor?', 'Can I consult a doctor online?', 'How can I view my prescription?', 'Can doctors manage their availability?', 'How does remote monitoring work?', 'How can I view my medical records?'];

export default function HomePage() {
    const [openFaq, setOpenFaq] = useState(0);
    const [sent, setSent] = useState(false);
    const doctors = getDoctors().slice(0, 3);
    return <div className="landing-page"><Navbar /><main>
        <section id="about" className="landing-hero"><div className="hero-grid"><div><div className="hero-kicker"><span className="pulse-dot" /> Care that moves with you</div><h1>Virtual Healthcare<br /><em>Consultation Platform</em></h1><p>Connect with qualified doctors, book virtual consultations, manage prescriptions, and monitor your health from anywhere.</p><div className="hero-actions"><Link to="/doctors"><Button size="lg">Find a doctor <ArrowRight size={17} /></Button></Link><Link to="/login" className="hero-secondary">Book consultation <CalendarCheck size={17} /></Link></div><div className="hero-trust"><ShieldCheck size={16} /> Frontend prototype with sample data · Built for modern care teams</div></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-card hero-card-main"><div className="hero-card-top"><span><span className="pulse-dot" /> Next consultation</span><strong>Today, 10:00 AM</strong></div><div className="hero-doctor"><div className="hero-avatar">RS</div><div><strong>Dr. Rahul Sharma</strong><span>Cardiologist · Video visit</span></div><span className="confirmed-badge">Confirmed</span></div><div className="hero-card-footer"><span><ClockIcon /> Starts in 2h 18m</span><Link to="/consultation"><Video size={15} /> Join room</Link></div></div><div className="hero-card hero-card-metric"><HeartPulse size={18} /><span>Health snapshot</span><strong>98<small>% SpO2</small></strong><em>Normal today</em></div><div className="hero-card hero-card-note"><span className="mini-check"><ShieldCheck size={14} /></span><div><strong>Care plan updated</strong><span>Prescription ready to review</span></div></div></div></div></section>
        <section className="landing-proof"><div><strong>10K+</strong><span>Patients supported</span></div><div><strong>500+</strong><span>Qualified doctors</span></div><div><strong>25K+</strong><span>Consultations managed</span></div><div><strong>98%</strong><span>Appointment success</span></div></section>
        <section className="landing-section" id="services"><div className="section-intro"><div><span className="section-kicker">One connected care experience</span><h2>Everything your care journey needs.</h2></div><p>From the first search to the follow-up plan, MediConnect gives patients, practitioners, and operations teams a shared place to move care forward.</p></div><div className="service-grid">{services.map(([title, description, Icon, tone]) => <div className={`landing-service ${tone}`} key={title}><div className="service-icon"><Icon size={21} /></div><h3>{title}</h3><p>{description}</p><button>Learn more <ArrowRight size={14} /></button></div>)}</div></section>
        <section className="landing-section soft-section"><div className="section-intro centered"><span className="section-kicker">How it works</span><h2>A calmer path to better conversations.</h2><p>Simple workflows keep the focus on the person receiving care.</p></div><div className="workflow-grid">{[['01', 'Find your practitioner', 'Search specializations, compare availability, and explore doctor profiles.'], ['02', 'Choose a time', 'Select a consultation type and reserve a convenient slot in the booking flow.'], ['03', 'Continue your care', 'Join a simulated consultation room, review records, and follow your care plan.']].map(([number, title, text]) => <div className="workflow-step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
        <section className="landing-section featured-section"><div className="section-intro"><div><span className="section-kicker">Care network</span><h2>Meet the people behind the care.</h2></div><Link to="/doctors" className="text-link">View all doctors <ArrowRight size={15} /></Link></div><div className="featured-doctors">{doctors.map((doctor) => <Link to={`/doctors/${doctor.id}`} className="featured-doctor" key={doctor.id}><img src={doctor.profileImage} alt={doctor.name} /><div><strong>{doctor.name}</strong><span>{doctor.specialization}</span><small><span className="pulse-dot" /> {doctor.status} · {doctor.experience} years experience</small></div><ArrowRight size={17} /></Link>)}</div></section>
        <section className="landing-section split-section"><div className="monitoring-preview"><div className="preview-heading"><div><span className="section-kicker">Remote monitoring</span><h2>See the trend, not just the number.</h2></div><DemoPill /></div><div className="preview-metrics"><div><span>Heart rate</span><strong>72 <small>BPM</small></strong><em>Normal</em></div><div><span>Blood pressure</span><strong>120/80</strong><em>Normal</em></div><div><span>Blood oxygen</span><strong>98<small>%</small></strong><em>Normal</em></div></div><div className="preview-chart">{[35, 55, 43, 66, 54, 74, 62, 84, 73, 91].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div></div><div className="split-copy"><span className="section-kicker">Why MediConnect</span><h2>Designed for trust at every handoff.</h2><p>A polished demonstration of a multi-vendor telemedicine experience, with clear boundaries between patient care, practitioner workflows, and operations.</p><div className="benefit-list"><span><ShieldCheck size={17} /> Sample data is clearly labelled</span><span><HeartPulse size={17} /> Care signals are easy to scan</span><span><Stethoscope size={17} /> Role-specific workspaces</span></div></div></section>
        <section className="landing-section architecture-banner"><div><span className="section-kicker">Platform blueprint</span><h2>One frontend view of a larger care network.</h2><p>Explore the represented services and planned boundaries behind MediConnect.</p></div><Link to="/architecture" className="light-button">View architecture <ArrowRight size={16} /></Link></section>
        <section className="landing-section faq-section"><div className="section-intro centered"><span className="section-kicker">Need to know</span><h2>Frequently asked questions.</h2></div><div className="faq-list">{faqs.map((question, index) => <div className={`faq-item ${openFaq === index ? 'open' : ''}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span><ChevronDown size={18} /></button>{openFaq === index && <p>{index === 0 ? 'Open Find doctors, choose a practitioner, select a slot, and confirm your demo appointment.' : index === 1 ? 'Yes. The consultation room is a frontend simulation that demonstrates the intended experience.' : 'Sign in to your patient workspace to review sample prescriptions and care instructions.'}</p>}</div>)}</div></section>
        <section className="landing-contact" id="contact"><div><span className="section-kicker">Stay connected</span><h2>Care starts with a conversation.</h2><p>Questions about the MediConnect prototype? Send the team a note.</p></div><form onSubmit={(event) => { event.preventDefault(); setSent(true); }}><div className="contact-row"><input aria-label="Name" placeholder="Your name" required /><input aria-label="Email" type="email" placeholder="Email address" required /></div><textarea aria-label="Message" placeholder="How can we help?" required /><Button type="submit">{sent ? 'Message sent' : 'Send message'} <ArrowRight size={16} /></Button></form></section>
    </main><footer className="landing-footer"><div className="sidebar-brand"><span className="brand-mark"><Stethoscope size={20} /></span><span>Medi<span>Connect</span></span></div><span>Frontend-only telemedicine prototype · Sample data for demonstration</span></footer></div>;
}
function ClockIcon() { return <span className="clock-icon">◷</span>; }
function DemoPill() { return <span className="demo-label"><span className="pulse-dot" /> Demo data</span>; }
